### ISSUE TITLE
Fatal error with Joomla 3.5-beta

### ISSUE THREAD

**Issue by danielsmink** [joomlatools/joomlatools-composer#21]
``` php
PHP Fatal error:  Uncaught RuntimeException: The session is not started. in /Users/danielsmink/projects/gmp.jos.picturae.pro/public/libraries/joomla/session/handler/native.php:229
Stack trace:
#0 /Users/danielsmink/projects/gmp.jos.picturae.pro/public/libraries/joomla/session/session.php(743): JSessionHandlerNative->save()
#1 /Users/danielsmink/projects/gmp.jos.picturae.pro/public/vendor/joomlatools/installer/src/Joomlatools/Composer/ExtensionInstaller.php(466): JSession->close()
#2 [internal function]: Joomlatools\Composer\ExtensionInstaller->__destruct()
#3 {main}
  thrown in /Users/danielsmink/projects/gmp.jos.picturae.pro/public/libraries/joomla/session/handler/native.php on line 229
```

**Comment by stevenrombauts** [comment]
Closing this issue as the first 3.5 stable release has fixed this by itself. Thanks Daniel!
